name: chat_engine
services:
#  sglang:
#    image: lmsysorg/sglang:v0.5.1.post3-cu126
#    container_name: sglang
#    restart: unless-stopped
#    ports:
#      - "${SGLANG_PORT:-30000}:30000"
#    volumes:
#      - sglang_models:/root/.cache/huggingface
#    environment:
#      CUDA_VISIBLE_DEVICES: "${CUDA_VISIBLE_DEVICES:-0}"
#    entrypoint: python3 -m sglang.launch_server
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [ gpu ]
#    command:
#      - "--model-path"
#      - "${MODEL_NAME:-Qwen/Qwen3-4B}"
#      - "--host"
#      - "0.0.0.0"
#      - "--port"
#      - "${SGLANG_PORT:-30000}"
#      - "--enable-metrics"
#      - "--quantization"
#      - "awq_marlin"
#      - "--mem-fraction-static"
#      - "${GPU_MEM_UTIL:-0.8}"

  sglang_embedding:
    image: lmsysorg/sglang:v0.5.1.post3-cu126
    container_name: sglang_embedding
    restart: unless-stopped
    ports:
      - "${SGLANG_EMBEDDING_PORT:-30001}:30001"
    volumes:
      - sglang_embedding_models:/root/.cache/huggingface
    environment:
      CUDA_VISIBLE_DEVICES: "${CUDA_VISIBLE_DEVICES:-0}"
    entrypoint: python3 -m sglang.launch_server
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    command:
      - "--model-path"
      - "${EMBEDDING_MODEL_NAME:-Qwen/Qwen3-Embedding-0.6B}"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${SGLANG_EMBEDDING_PORT:-30001}"
      - "--enable-metrics"
      - "--is-embedding"
      - "--mem-fraction-static"
      - "${EMBEDDING_GPU_MEM_UTIL:-0.4}"
volumes:
  sglang_models:
  sglang_embedding_models: