from .settings import settings

# API Config
API_VERSION = settings.API_VERSION
NUM_WORKERS = settings.NUM_WORKERS
SERVING_API_KEY = settings.SERVING_API_KEY
FASTAPI_API_KEY = settings.FASTAPI_API_KEY

# External API Keys
UNDATASIO_API_KEY = settings.UNDATASIO_API_KEY
LLAMAPARSE_API_KEY = settings.LLAMAPARSE_API_KEY
UNSTRUCTURED_API_KEY = settings.UNSTRUCTURED_API_KEY
UNSTRUCTURED_API_URL = settings.UNSTRUCTURED_API_URL

# Parsing provider selection ("llamaparse")
PDF_PARSER_PROVIDER = settings.PDF_PARSER_PROVIDER