import os
from dotenv import load_dotenv

# Load the .env file
load_dotenv()

# API key
SERVING_API_KEY = os.getenv("SERVING_API_KEY")
FASTAPI_API_KEY = os.getenv("FASTAPI_API_KEY")
EMBEDDING_SERVING_SERVICE_NAME = os.getenv("EMBEDDING_SERVING_SERVICE_NAME")

# Other service
UNDATASIO_API_KEY = os.getenv("UNDATASIO_API_KEY")
# Postgres configuration
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")

# Minio configuration
MINIO_ROOT_USER = os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = os.getenv("MINIO_ROOT_PASSWORD")

# MLflow service
MLFLOW_EXPERIMENT_NAME = os.getenv("MLFLOW_EXPERIMENT_NAME")
MLFLOW_DEFAULT_ARTIFACT_ROOT = os.getenv("MLFLOW_DEFAULT_ARTIFACT_ROOT")
MLFLOW_S3_ENDPOINT_URL = os.getenv("MLFLOW_S3_ENDPOINT_URL")